version: '3'

networks:
    nginx-php-mysql8:

services:

    # nginx
    nginx:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "80:80"
        volumes:
            - ../projects/php5-test-project1:/var/www/project1
            - ../projects/php5-test-project2:/var/www/project2
            - ./nginx/website1.conf:/etc/nginx/conf.d/website1.conf
            - ./nginx/website2.conf:/etc/nginx/conf.d/website2.conf
        depends_on:
            - php-service1
            - php-service2
            - mysql8-service
        networks:
            - nginx-php-mysql8

    # php
    php1:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: website1
        privileged: true
        volumes:
            - ../projects/php5-test-project1:/var/www/project1
        networks:
            - nginx-php-mysql8
        depends_on: 
            - mysql8

     # php
    php2:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: website2
        privileged: true
        volumes:
            - ../projects/php5-test-project2:/var/www/project2
        networks:
            - nginx-php-mysql8
        depends_on: 
            - mysql8

    # mysql
    mysql8:
        image: mysql:8
        container_name: mysql8-container
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_USER: ${db_user}
            MYSQL_ROOT_PASSWORD: ${db_root_pass}
            MYSQL_PASSWORD: ${db_user_pass}
        networks:
            - nginx-php-mysql8
