version: '3'

networks:
    nginx-php-mysql8:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "80:80"
        volumes:
            - ./website1:/var/www/project1
            - ./website2:/var/www/project2
            - ./nginx/website1.conf:/etc/nginx/conf.d/website1.conf
            - ./nginx/website2.conf:/etc/nginx/conf.d/website1.conf
        depends_on:
            - php-service1
            - php-service2
            - mysql8-service
        networks:
            - nginx-php-mysql8

    # php
    php-service1:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php-container
        ports:
            - "9000:9000"
        volumes:
            - ./website1:/var/www/project1
        networks:
            - nginx-php-mysql8

     # php
     php-service2:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php-container
        ports:
            - "9000:9000"
        volumes:
            - ./website2:/var/www/project2
        networks:
            - nginx-php-mysql8

    # mysql
    mysql8-service:
        image: mysql:8
        container_name: mysql8-container
        ports:
            - "4306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
        networks:
            - nginx-php-mysql8